import numpy as np
from typing import Tuple
import cv2
from rembg import remove


def crop_image(image: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """
    Crop the input image based on a mask generated by the 'rembg' library using the 'u2net' model.

    Parameters:
    image (numpy.ndarray): The input image to be cropped.

    Returns:
    tuple[numpy.ndarray, numpy.ndarray]: A tuple containing the cropped image and the mask used for cropping.
        - The cropped image is a numpy array representing the cropped region of the input image.
        - The mask is a numpy array representing the binary mask used for cropping, with white pixels (255) indicating the cropped region and black pixels (0) indicating the background.
    """
    mask = remove(image, only_mask=True, m="u2netp")

    image_cropped = cv2.bitwise_and(image, image, mask=mask)

    mask = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)

    return image_cropped, mask
